---

- name: Create temp directory
  file:
    path: "{{ workstation_tempdir }}"
    state: directory
    mode: 0755

- name: Install Pre-reqs
  package:
    name: "{{ item }}"
  with_items:
    - tar
#    - gcc
#    - kernel-headers
#    - kernel-devel
#    - glibc-headers

- name: Download workstation
  get_url:
    url: "{{ workstation_download_url }}"
    dest: "{{ workstation_tempdir }}/tryworkstation-linux-64.sh"
    validate_certs: "{{ workstation_download_validate_certs }}"

- name: Mark script executable
  file:
    path: "{{ workstation_tempdir }}/tryworkstation-linux-64.sh"
    state: file
    mode: 0755

- name: Run installer
  shell: >
    {{ workstation_tempdir }}/tryworkstation-linux-64.sh --eulas-agreed --console
    --required {{'--set-setting vmware-workstation serialNumber '+ workstation_license if workstation_license is defined else '' }}
  args:
    creates: /usr/bin/vmware
  become: yes
  tags:
    - skip_ansible_lint
